### ISSUE TITLE
Readability of Merge Strategies page

### ISSUE THREAD

**Issue by mistic100** [git/git-scm.com#701]
Hello

I had an hard time understanding the "ours" merge strategy because on this page http://git-scm.com/docs/merge-strategies it's difficult to immediately understand that the first occurrence of "ours" is an option of "recursive" (when you are in a rush you don't read everything :smile: )

I suggest to improve readability by simple increasing the indentation of the strategies options paragraphs and perhaps adding a light left border.

Example :
![fireshot screen capture 086 - git - merge-strategies documentation - git-scm_com_docs_merge-strategies](https://cloud.githubusercontent.com/assets/41597/13682601/c0a8f32c-e702-11e5-9a7f-d9ef107ce152.png)

``` css
dd>.dlist {
    padding-left: 1em;
    border-left: 1px solid rgb(221, 221, 221);
}
```

Thank you
